# Ansible inventory — prod environment

[prod]
prod-server-01 ansible_host=10.10.3.10 ansible_user=deploy
prod-server-02 ansible_host=10.10.3.11 ansible_user=deploy
prod-server-03 ansible_host=10.10.3.12 ansible_user=deploy

[prod:vars]
ansible_python_interpreter=/usr/bin/python3
registry_host=registry.company.com
# In prod, enable strict host checking — add host fingerprints to known_hosts
# ansible_ssh_common_args='-o StrictHostKeyChecking=yes'
