apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
  namespace: apps
  labels:
    app.kubernetes.io/part-of: progressive-delivery
spec:
  args:
    - name: service
  metrics:
    - name: error-rate
      initialDelay: 45s
      interval: 30s
      count: 3
      consecutiveErrorLimit: 8
      successCondition: result[0] <= 0.05
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status=~"5..",service="{{args.service}}"}[2m]))
            /
            sum(rate(http_requests_total{service="{{args.service}}"}[2m]))
