apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-p99
  namespace: apps
  labels:
    app.kubernetes.io/part-of: progressive-delivery
spec:
  args:
    - name: service
  metrics:
    - name: latency-p99
      initialDelay: 45s
      interval: 30s
      count: 3
      consecutiveErrorLimit: 8
      successCondition: result[0] <= 1.0
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.99,
              sum(rate(http_request_duration_seconds_bucket{service="{{args.service}}"}[2m])) by (le)
            )
