apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: apps
  labels:
    app.kubernetes.io/part-of: progressive-delivery
spec:
  args:
    - name: service
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status="200",service="{{args.service}}"}[2m]))
            /
            sum(rate(http_requests_total{service="{{args.service}}"}[2m]))
