# Ansible inventory — pre environment

[pre]
pre-server-01 ansible_host=10.10.2.10 ansible_user=deploy
pre-server-02 ansible_host=10.10.2.11 ansible_user=deploy

[pre:vars]
ansible_python_interpreter=/usr/bin/python3
registry_host=registry.company.com
